--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "KH"."CAFE" DROP CONSTRAINT "CAFE_ID_PK";

DROP INDEX "KH"."CAFE_NAME_UK";

DROP INDEX "KH"."CAFE_ID_PK";

DROP TABLE "KH"."CAFE";

CREATE TABLE "KH"."CAFE" (
		"ID" NUMBER NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL,
		"PRICE" NUMBER NOT NULL,
		"ISICE" VARCHAR2(1)
	);

CREATE UNIQUE INDEX "KH"."CAFE_NAME_UK" ON "KH"."CAFE" ("NAME" ASC);

CREATE UNIQUE INDEX "KH"."CAFE_ID_PK" ON "KH"."CAFE" ("ID" ASC);

ALTER TABLE "KH"."CAFE" ADD CONSTRAINT "CAFE_ID_PK" PRIMARY KEY ("ID");

